### ISSUE TITLE
uti_plot_init not available from radtrack/srw/uti_plot.py

### ISSUE THREAD

**Issue by MZHarrison** [radiasoft/radtrack#112] opened 2015-06-17 01:19 UTC
When RbGlobal (when run in Windows) tries to load the RbSrwTab, I get the following error:

    Traceback (most recent call last):
      File "radtrack/RbGlobal.py", line 22, in <module>
        from radtrack.RbSrwTab import RbSrwTab
      File "c:\users\mark harrison\documents\github\radtrack\radtrack\RbSrwTab.py", line 3, in <module>
        from radtrack import srw_multi_particle
      File "c:\users\mark harrison\documents\github\radtrack\radtrack\srw_multi_particle.py", line 29, in <module>
        from radtrack import srw_params
      File "c:\users\mark harrison\documents\github\radtrack\radtrack\srw_params.py", line 13, in <module>
        from radtrack.rt_srwlib import srwlib, uti_plot
      File "c:\users\mark harrison\documents\github\radtrack\radtrack\rt_srwlib.py", line 18, in <module>
        uti_plot.uti_plot_init(backend=uti_plot.DEFAULT_BACKEND, fname_format=None)
    AttributeError: 'module' object has no attribute 'uti_plot_init'

If this means I need to install SRW natively and the radtrack.srw is deprecated, so be it. I could use a pointer to some instructions for getting it to work.

**Comment by robnagler** [comment] 2015-06-17 01:25
This is caused by the version of srw that's checked into
radtrack/radtrack/srw. This needs to be removed. It's a very old version,
and it doesn't have the latest uti_plot*.py.

You should install SRW from github.com/radiasoft/SRW. I have not built it
on Windows.

Rob

**Comment by bruhwile** [comment] 2015-06-22 21:42
Hi Mark,

Did you sort this out?

Yes, it's now required that SRW be installed natively on Windows.

I have this working on my PC. For SRW, you need to get the latest version
from
   https://github.com/ochubar/SRW
or
   https://github.com/radiasoft/SRW

and then copy the following files over to the
   .../site-packages/
directory of your Windows python install:
  srw.lib
  srwl*.py
  uti_*.py

Also, you have to copy over the correct *.pyd file and rename it, or else
build it yourself.
For 32-bit Python 2.7, you have to get the file
    srwlpy2_win32.pyd
from the SRW repository and copy it into your site-packages/ directory with
the name
    srwlpy.pyd

Going through the code this morning, I thought the code for importing SRW
was very confusing, so I cleaned things up a bit.

The following files have been deleted from the repository:
   .../radtrack/srw/srwlib.py
   .../radtrack/srw/srwlpy.pyd
because they were both out of date.

Best,
David

**Comment by MZHarrison** [comment] 2015-06-23 02:44
I've got it working on Windows and the vagrant client.

**Closed** 2015-06-23 03:39 UTC
